petshop/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace petshop.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }

        [Required(ErrorMessage = "Informe seu nome completo")]
        [MinLength(3)]
        [MaxLength(100)]
        public string FullName { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(200)]
        public string Address { get; set; }

        [Required]
        [MinLength(3)]
        [MaxLength(100)]
        public string State { get; set; }

        [Required]
        [MinLength(3)]
        [MaxLength(100)]
        public string City { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Total { get; set; }
        public int TotalOrderItems { get; set; }
        public DateTime OrderSent { get; set; }
        public DateTime? OrderReceived { get; set; }
        public List<OrderDetail> CartItems { get; set; }
    }
}

petshop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using petshop.Models;
using petshop.Repositories.Interfaces;
using petshop.ViewModels;

namespace petshop.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly Cart _cart;

        public CartController(IProductRepository productRepository, Cart cart)
        {
            _productRepository = productRepository;
            _cart = cart;
        }

        public IActionResult Index()
        {
            var items = _cart.GetCartItems();
            _cart.CartItems = items;

            CartViewModel cartViewModel = new CartViewModel
            {
                Cart = _cart,
                CartTotal = _cart.GetCartTotal()
            };

            return View(cartViewModel);
        }

        public RedirectToActionResult AddCartItem(int productId)
        {
            var product = _productRepository.GetProductById(productId);

            if (product != null)
            {
                _cart.AddItemToCart(product);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoveCartItem(int productId)
        {
            var product = _productRepository.GetProductById(productId);

            if (product != null)
            {
                _cart.RemoveItemFromCart(product);
            }

            return RedirectToAction("Index");
        }
    }
}

petshop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using petshop.Models;
using petshop.Repositories.Interfaces;

namespace petshop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly Cart _cart;

        public OrderController(IOrderRepository orderReository, Cart cart)
        {
            _orderRepository = orderReository;
            _cart = cart;
        }

        [HttpGet]
        public IActionResult Checkout() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ckeckout(Order order)
        {
            int orderTotalItems = 0;
            decimal orderTotalPrice = 0.0m;

            //Obtém os itens do carrinho de compra
            List<CartItem> cartItems = _cart.GetCartItems();
            _cart.CartItems = cartItems;

            // Verifica se existem itens de pedido
            if (_cart.CartItems.Count > 0)
            {
                ModelState.AddModelError("", "Seu carrinho está vazio");
            }

            // Calculando o total de itens e o total de pedidos
            foreach (var item in cartItems)
            {
                orderTotalItems += item.Quantity;
                orderTotalPrice += item.Product.Price * item.Quantity;
            }

            // Atribui os valores obtidos ao pedido
            order.Total = orderTotalPrice;
            order.TotalOrderItems = orderTotalItems;

            // Valida os dados do pedido
            if (ModelState.IsValid)
            {
                // Cria os pedidos
                _orderRepository.CreateOrder(order);

                ViewBag.CheckoutCompleted = "Obrigado por comprar conosco!";
                ViewBag.TotalOrder = _cart.GetCartTotal();

                // Limpa o carrinho
                _cart.CleanCart();

                return View("~/Views/Order/OrderCompleted.cshtml", order);
            }

            return View(order);
        }
    }
}

petshop/Views/Order/Checkout.cshtml
@model Order

<h3>Finalize seu pedido!</h3>
<hr />
<form asp-controller="Order" asp-action="Checkout" method="POST">
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="FullName" class="control-label"></label>
            <input asp-for="FullName" class="form-control"/>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="Address" class="control-label"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="State" class="control-label"></label>
            <input asp-for="State" class="form-control" />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="City" class="control-label"></label>
            <input asp-for="City" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="form-group col-md-3">
            <input class="btn btn-success" type="submit" value="Concluir pedido"/>
        </div>
        &nbsp
        <div class="form-group col-md-3">
            <a class="btn btn-outline-info" asp-controller="Cart" asp-action="index" value="Concluir pedido">Retornar ao carrinho</a>
        </div>
    </div>
</form>

petshop/Views/Order/OrderCompleted.cshtml
@model Order

<div class="jumbotron">
    <h2>@ViewBag.CheckoutCompleted</h2>
</div>
<div class="card">
    <div class="card-body">
        <p>CLiente: <strong>@Model.FullName</strong></p>
        <p>Data do pedido: <strong>@Model.OrderSent</strong></p>
        <p>Número do pedido: <strong>@Model.OrderId</strong></p>
    </div>
</div>