petshop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using petshop.Models;
using petshop.Repositories.Interfaces;
using petshop.ViewModels;

namespace petshop.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly Cart _cart;

        public CartController(IProductRepository productRepository, Cart cart)
        {
            _productRepository = productRepository;
            _cart = cart;
        }

        public IActionResult Index()
        {
            var items = _cart.GetCartItems();
            _cart.CartItems = items;

            CartViewModel cartViewModel = new CartViewModel
            {
                Cart = _cart,
                CartTotal = _cart.GetCartTotal()
            };

            return View(cartViewModel);
        }

        public RedirectToActionResult AddCartItem(int productId)
        {
            var product = _productRepository.GetProductById(productId);

            if (product != null)
            {
                _cart.AddItemToCart(product);
            }

            return RedirectToAction("Index");
        }

        public IActionResult RemoveCartItem(int productId)
        {
            var product = _productRepository.GetProductById(productId);

            if (product != null)
            {
                _cart.RemoveItemFromCart(product);
            }

            return RedirectToAction("Index");
        }
    }
}

petshop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using petshop.Models;
using petshop.Repositories.Interfaces;
using petshop.ViewModels;

namespace petshop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;

        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public IActionResult List(string category)
        {
            IEnumerable<Product> products;
            string currentCategory = String.Empty;

            if (String.IsNullOrEmpty(category)) 
            {
                products = _productRepository.AllProducts.OrderBy(p => p.Id);
                currentCategory = "Todos os produtos";
            } else
            {
                products = _productRepository.AllProducts.Where(p => p.Category.Name == category);
                currentCategory = category;
            }

            var productViewModel = new ProductListViewModel();
            productViewModel.Products = products;
            productViewModel.Category= currentCategory;

            return View(productViewModel);
        }
        public IActionResult Detail(int productId)
        {
            var product = _productRepository.GetProductById(productId);
            return View(product);
        }
        public ViewResult Search(string productName)
        {
            IEnumerable<Product> products;  
            string currentCategory = String.Empty;

            if(String.IsNullOrEmpty(productName)) 
            {
                products = _productRepository.AllProducts.OrderBy(p => p.Name);
                currentCategory = "Todos os produtos";
            } else
            {
                products = _productRepository.AllProducts.Where(p => p.Name.ToLower().Contains(productName.ToLower()));

                if (products.Any()) 
                {
                    currentCategory = "Produtos";
                } else
                {
                    currentCategory = "Nenhum produto encontrado";
                }
            }

            ProductListViewModel productListViewModel = new ProductListViewModel()
            {
                Products = products,
                Category = currentCategory,
            };

            return View("~/Views/Product/List.cshtml", productListViewModel);
        }
    }
}

petshop/Views/Shared/_Banner.cshtml
<div id="banner" class="carousel slide">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/banner.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#banner" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#banner" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

petshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Petshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/petshop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Petshop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">                  
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        @await Component.InvokeAsync("CategoryMenu")
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contato</a>
                        </li>
                        <form class="navbar-form" asp-controller="Product" asp-action="Search" method="GET">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Procurando por algum produto?" name="productName" />
                            </div>
                        </form>
                    </ul>   
                    @await Component.InvokeAsync("CartResume")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Petshop
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

petshop/Views/Shared/_ProductCard.cshtml
@model Product

<div class="col-sm-4 col-md-4 col-lg-4">
    <img src="~/images/@Model.ImageURL" class="img-fluid" />
    <p>@Model.Price</p>
    <a asp-controller="Product" asp-action="Detail" asp-route-productId="@Model.Id">@Model.Name</a>
    <p>@Model.ShortDescription</p>
    <a 
        class="btn btn-primary" 
        asp-controller="Cart" 
        asp-action="AddCartItem"
        asp-route-productId="@Model.Id">
        Adicionar no carrinho
    </a>
</div>